name: Launch ClickHouse Deployment
on:
  workflow_dispatch:
    inputs:
      hardware_config:
        description: 'Hardware config (format: CPUcores,RAMgb) - e.g. 16,64'
        required: true
        default: '16,64'
      cluster_config:
        description: 'Cluster config (format: name,shards,replicas) - e.g. clickhouse_cluster,1,3'
        required: true
        default: 'clickhouse_cluster,1,3'
      clickhouse_version:
        description: 'ClickHouse version'
        required: true
        default: '25.3.2.39'
      keeper_ips:
        description: 'ClickHouse Keeper IPs (comma separated)'
        required: true
      server_ips:
        description: 'ClickHouse Server IPs (comma separated)'
        required: true
      ssh_config:
        description: 'SSH config (format: username,base64_key)'
        required: true
      environment:
        description: 'Environment (development, testing, production)'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - testing
          - production
      hardware_profile:
        description: 'Hardware profile'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - small
          - medium
          - large
          - custom
      ssl_enabled:
        description: 'Enable SSL'
        required: true
        default: true
        type: boolean
jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Parse inputs
        id: parse
        run: |
          # Parse hardware config
          echo "cpu_cores=$(echo '${{ github.event.inputs.hardware_config }}' | cut -d ',' -f 1)" >> $GITHUB_OUTPUT
          echo "ram_gb=$(echo '${{ github.event.inputs.hardware_config }}' | cut -d ',' -f 2)" >> $GITHUB_OUTPUT
          
          # Parse cluster config
          echo "cluster_name=$(echo '${{ github.event.inputs.cluster_config }}' | cut -d ',' -f 1)" >> $GITHUB_OUTPUT
          echo "shard_count=$(echo '${{ github.event.inputs.cluster_config }}' | cut -d ',' -f 2)" >> $GITHUB_OUTPUT
          echo "replica_count=$(echo '${{ github.event.inputs.cluster_config }}' | cut -d ',' -f 3)" >> $GITHUB_OUTPUT
          
          # Parse SSH config
          echo "ssh_user=$(echo '${{ github.event.inputs.ssh_config }}' | cut -d ',' -f 1)" >> $GITHUB_OUTPUT
          echo "ssh_key=$(echo '${{ github.event.inputs.ssh_config }}' | cut -d ',' -f 2-)" >> $GITHUB_OUTPUT

      - name: Trigger deployment workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: rakeshtherani/Clickhouse-Custom-Ansible-Project-v1
          event-type: deploy-clickhouse
          client-payload: |
            {
              "cpu_cores": "${{ steps.parse.outputs.cpu_cores }}",
              "ram_gb": "${{ steps.parse.outputs.ram_gb }}",
              "clickhouse_version": "${{ github.event.inputs.clickhouse_version }}",
              "cluster_name": "${{ steps.parse.outputs.cluster_name }}",
              "shard_count": "${{ steps.parse.outputs.shard_count }}",
              "replica_count": "${{ steps.parse.outputs.replica_count }}",
              "keeper_ips": "${{ github.event.inputs.keeper_ips }}",
              "server_ips": "${{ github.event.inputs.server_ips }}",
              "ssh_user": "${{ steps.parse.outputs.ssh_user }}",
              "ssh_key": "${{ steps.parse.outputs.ssh_key }}",
              "environment": "${{ github.event.inputs.environment }}",
              "hardware_profile": "${{ github.event.inputs.hardware_profile }}",
              "ssl_enabled": "${{ github.event.inputs.ssl_enabled }}"
            }
